#!/bin/bash

if [[ ${1} =~ ^[0-9]+$ ]] && [[ ${2} =~ ^[0-9]+$ ]] && [[ ${3} =~ ^[0-9]+$ ]] ;
then
for (( i = 0; i < $((${3})); i++)) ; do
	say "timer start"
	for (( x = 0; x < $((${1})); x++)) ; do
		echo ${x}
		sleep 60
	done
	say "take a break"
	for (( x = 0; x < $((${2})); x++)) ; do
		echo ${x}
		sleep 60
	done
done
say "good job"
fi
